services:
  - type: web
    name: sistema-isp
    runtime: python
    plan: free
    rootDir: sistema_isp/projeto_django_backup
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: .