# Generated by Django 6.0.4 on 2026-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('tecnologia', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provedores',
            },
        ),
    ]
