# Generated by Django 6.0.4 on 2026-09-15 15:29

import django.db.models.deletion
from django.db import migrations, models
from providers.migration_operations import CreateOrValidateLegacyModel


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_prestador_servico'),
    ]

    operations = [
        CreateOrValidateLegacyModel(
            name='ContratoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('velocidade', models.CharField(max_length=50)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('meio_fisico', models.CharField(max_length=50)),
                ('mensal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'providers_contratocusto',
            },
        ),
        CreateOrValidateLegacyModel(
            name='InboxContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('dados_extraidos', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        CreateOrValidateLegacyModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('parceiro_bst', models.BooleanField(default=False)),
                ('fibra', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('link_dedicado', models.BooleanField(default=False)),
                ('link_banda_larga', models.BooleanField(default=False)),
                ('zona_rural', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        CreateOrValidateLegacyModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='providers.provedor')),
            ],
        ),
        CreateOrValidateLegacyModel(
            name='CidadeAtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='providers.provedor')),
            ],
            options={
                'indexes': [models.Index(fields=['nome', 'uf'], name='providers_c_nome_9698da_idx')],
                'unique_together': {('provedor', 'nome', 'uf')},
            },
        ),
    ]
