# Generated by Django 6.0.4 on 2026-05-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provedor',
            old_name='data_registro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='provedor',
            old_name='nome_fantasia',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='tecnologia',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='uf',
        ),
        migrations.AddField(
            model_name='provedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='fibra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provedor',
            name='link_banda_larga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provedor',
            name='link_dedicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provedor',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='zona_rural',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='provedor',
            table=None,
        ),
        migrations.CreateModel(
            name='CidadeAtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='providers.provedor')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('prioridade', models.CharField(default='S', max_length=1)),
                ('valor_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aval_retorno', models.IntegerField(default=0)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='providers.provedor')),
            ],
        ),
    ]
