# Generated by Django 6.0.4 on 2026-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_data_registro_provedor_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidadeatendida',
            old_name='cidade',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='contato',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
