# Generated by Django 6.0.4 on 2026-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provedor_parceiro_bst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadeatendida',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cidadeatendida',
            name='uf',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
