# Generated by Django 6.0.4 on 2026-05-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_cidadeatendida_nome_alter_cidadeatendida_uf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_custos', to='providers.provedor')),
            ],
        ),
    ]
