# Generated by Django 6.0.4 on 2026-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_historicocusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('servico', models.CharField(max_length=100)),
                ('ip_fixo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_mb', models.IntegerField(help_text='Velocidade em MB')),
                ('vigencia_meses', models.IntegerField()),
            ],
        ),
    ]
