# Generated by Django 6.0.4 on 2026-05-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_contratocusto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cidadeatendida',
            index=models.Index(fields=['nome', 'uf'], name='providers_c_nome_9698da_idx'),
        ),
    ]
