# Generated by Django 6.0.4 on 2026-06-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_cidadeatendida_providers_c_nome_9698da_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provedor',
            options={'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
    ]
