# Generated by Django 6.0.4 on 2026-06-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_cidadeatendida_providers_c_nome_9698da_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provedor',
            options={'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='aval_retorno',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='valor_medio',
        ),
        migrations.AlterField(
            model_name='contato',
            field=models.IntegerField(default=1),
        ),
    ]
