# Generated by Django 6.0.4 on 2026-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_alter_provedor_options_remove_contato_aval_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='prioridade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
