# Generated by Django 6.0.4 on 2026-06-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_alter_provedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocusto',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_custos', to='providers.provedor'),
        ),
    ]
