# Generated by Django 6.0.4 on 2026-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_alter_contato_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='prioridade',
            field=models.IntegerField(default=1),
        ),
    ]
