# Generated by Django 6.0.4 on 2026-06-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_alter_historicocusto_provedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoCusto',
        ),
    ]
