# Generated by Django 6.0.4 on 2026-06-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_providers_contratocusto_delete_contratocusto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providers_contratocusto',
            table='providers_contratocusto',
        ),
    ]
