# Generated by Django 6.0.4 on 2026-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_providers_contratocusto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('dados_extraidos', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
