# Generated by Django 6.0.4 on 2026-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_rename_cidade_cidadeatendida_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='parceiro_bst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='cidadeatendida',
            unique_together={('provedor', 'nome', 'uf')},
        ),
    ]
